### ISSUE TITLE
Nick Command

### ISSUE THREAD

**Issue by 089OmegaGamer089** [NeilDevolopment/BeepBoopBot#1]
In your bot when nick command use so this error comes:-
`Command raised an exception: Forbidden: 403 Forbidden (error code: 50013): Missing Permissions`
Code:-
```@command.command()
async def nick(self, ctx, member: discord.Member,*,name):
  await member.edit(nick=name)
  embed = discord.Embed(title='Nick Name Successfully Changed!')
  await ctx.send(embed=embed)```

**Comment by Neilisop** [comment]
I'm sorry to hear that something isn't working with the bot, though I can not help you with this. You need to make a bug report issue from https://github.com/NeilDevolopment/BeepBoopBot/issues/new/choose.

**Locked.**
