### ISSUE TITLE
[Bug] Nick Command

### ISSUE THREAD

**Issue by 089OmegaGamer089** [NeilDevolopment/BeepBoopBot#2]
**Describe the bug**
After using this command It not works and when I checked terminal the error was there missing permission.Where as I was having Owner role and all perms.

**To Reproduce**
1. Start bot
2. Run command !nick OmegaGamer089#5812 Omega
**Expected behavior**
After start of bot if the admin use this command to nick the member and the member are not allowed to nick there name by themself.
**Desktop (please complete the following information):**
 - OS: Window 10
 - Bot Version 0.6

**Additional context**
Giveaway command not works

**Comment by Neilisop** [comment]
Hello, I'm sorry to hear that one of our commands do not work. This is a error on your end and it's not our fault. There's a missing permission error for the BOT not YOU. The next time you make a bug report thread give the error not just say "there's a missing permission error". 
**Steps to fix:**
Here's how you can fix the error.
1. Give the bot permissions to manage nicknames.
2. Make sure the bot's role is above the person's role you're trying to nick(basicly if you have a member role drag the bots role above the members role and then try to nick them)
