### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by KNIGHTOP006** [NeilDevolopment/BeepBoopBot#3]
Its written "Welcome to the UltimateCoreBot wiki!" instead of "Welcome to the BeepBoopBot wiki!" 
![image](https://user-images.githubusercontent.com/85861035/129447469-e8776074-808a-4e4c-8ed3-17582a4cc49a.png)

**Comment by Neilisop** [comment]
Please use the format.

**Comment by Neilisop** [comment]
Ok I'll just not force you to do it, I get what you're trying to say. The bug has been closed though for next time please stick to using the format if you find any bugs with-in the bot itself.

**Locked.**
