### ISSUE TITLE
Setup.py needs updates

### ISSUE THREAD

**Issue by Neilisop** [NeilDevolopment/BeepBoopBot#4]
Yes, I'm the owner of this project but this is completely honest.

We have gotten down to a solution, to view our plan click [here](https://github.com/NeilDevolopment/BeepBoopBot/issues/4#issuecomment-995648523)

**Is your feature request related to a problem? Please describe. (Optional)**
I'll be honest, the setup needs more updates and needs to be more user-friendly. You only get one choice, if you want logs or not and the text is not the best and can be better

**Describe the solution you'd like (Optional)**
Someone to change the text and make it better. It's not the best and it'd be great if the user knew how how get the information without visiting a webpage and you the configuration webpage is also fairly confusing for a starter

**Describe alternatives you've considered**
Maybe remove the you're gonna do this manually warning and add the stuff into the setup file & rename the wiki to manual configuration

**Additional context**

**Comment by Neilisop** [comment]
@TrueGamerTalha @089OmegaGamer089 Please read the entire thing and so reply to it. Do some fixes if you want.

**Comment by TrueGamerTalha** [comment]
# So... I have not checked the setup message yet. I will look at it and give some ideas.

## Saludos (Regards)

**Comment by Neilisop** [comment]
I'm thinking we add a tutorial, setup, Both(Setup and Tutorial) option. 

If they pick tutorial we can give them information on how to get the information needed for the setup. If they pick setup, we just run the setup like it is at the moment. If they pick both, we will run the setup normally but add information on how to get the information under every input or above.

How does that sound?

**Comment by Neilisop** [comment]
I'm wanting to do this change so a new user has an interactive setup and can get their own bot setup in no time!

**Comment by TrueGamerTalha** [comment]
Yes. This idea would be great!

**Comment by Neilisop** [comment]
Thanks! You should check my fork out https://github.com/neilisop/BeepBoopBot to see how the current things are going.

**Comment by Neilisop** [comment]
I'll update you with more information if needed, once done I'll make a pull request for you or @089OmegaGamer089 to review
